//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calc_from_geometryOfMotor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("calc_from_geometryOfMotor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %%%%% ADVISOR data file:  {MOTOR_NAME}
        ///%
        ///% Data confidence level: Model
        ///%
        ///% Notes:
        ///% 
        ///%
        ///% Created on: {CREATED_DATE}
        ///% By: Ngo Phuong Le
        ///%
        ///% Revision history at end of file.
        ///%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ///
        ///%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ///% FILE ID INFO
        ///%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ///mc_version=2003;
        ///mc_description=&apos;&apos;;
        ///mc_proprietary=0; % 0=&gt; non-proprietary, 1=&gt; proprietary, do not distribute
        ///mc_validation=0; % 0=&gt; no valid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string advisor_MC {
            get {
                return ResourceManager.GetString("advisor_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;b&quot;:-2.3,&quot;h&quot;:-234024.7513},{&quot;b&quot;:-2.25,&quot;h&quot;:-197751.6043},{&quot;b&quot;:-2.2,&quot;h&quot;:-159968.5693},{&quot;b&quot;:-2.15,&quot;h&quot;:-124329.4105},{&quot;b&quot;:-2.1,&quot;h&quot;:-88477.4846},{&quot;b&quot;:-2.05,&quot;h&quot;:-53589.44688},{&quot;b&quot;:-2,&quot;h&quot;:-31313.49588},{&quot;b&quot;:-1.95,&quot;h&quot;:-21249.42062},{&quot;b&quot;:-1.9,&quot;h&quot;:-16041.48364},{&quot;b&quot;:-1.85,&quot;h&quot;:-12486.93162},{&quot;b&quot;:-1.8,&quot;h&quot;:-9708.81567},{&quot;b&quot;:-1.75,&quot;h&quot;:-7448.318413},{&quot;b&quot;:-1.7,&quot;h&quot;:-5591.10689},{&quot;b&quot;:-1.65,&quot;h&quot;:-4053.653117},{&quot;b&quot;:-1.6,&quot;h&quot;:-2801.217421},{&quot;b&quot;:-1.55,&quot;h&quot;:-1813.085468},{&quot;b&quot;:-1.5,&quot;h&quot;:-1108.325569},{&quot;b&quot;:-1.45,&quot;h&quot;:-674.911968},{&quot;b&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bhsample {
            get {
                return ResourceManager.GetString("bhsample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log4net&gt;
        ///    &lt;appender name=&quot;Console&quot; type=&quot;log4net.Appender.ConsoleAppender&quot;&gt;
        ///        &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///            &lt;!-- Pattern to output the caller&apos;s file name and line number --&gt;
        ///            &lt;conversionPattern value=&quot;[%date] %-5level:  %message%newline&quot; /&gt;
        ///        &lt;/layout&gt;
        ///		&lt;filter type=&quot;log4net.Filter.LevelRangeFilter&quot;&gt;
        ///			&lt;levelMin value=&quot;DEBUG&quot; /&gt;
        ///			&lt;levelMax value=&quot;FATAL&quot; /&gt;
        ///		&lt;/filter&gt;
        ///    &lt;/appender&gt;
        ///    
        ///    &lt;appender name=&quot;RollingFile&quot; type=&quot;log4net.App [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log4net_config {
            get {
                return ResourceManager.GetString("log4net_config", resourceCulture);
            }
        }
    }
}
